### PR TITLE
Restart streams after Reddit error

### PR DESCRIPTION
**Pull request by Kartoffel**
I found that after 2-3 days the stream would stop reading new posts.
Some digging revealed that after Reddit was unavailable for a bit, PRAW would give up and the streams would not read any new posts.

I've added some delay after an exception (most likely caused by a 503 error on Reddit's side), after which the streams are restarted.

### CODE REVIEW

**Comment by bag-man** [comment]
Beautiful, well done :)

**Comment by bag-man** [comment]
@Kartoffel Are you having issues where it suddenly posts everything it's seen all at once?

**Comment by Kartoffel** [comment]
Periodically, or all the time?

**Comment by bag-man** [comment]
Periodically, it just happened for me. Been running six days. 

image


I had a MaxExecTime of 7 days in my systemd unit file so I'm hoping it was that.

**Comment by Kartoffel** [comment]
That's probably got to do with your _newpost.service_, where you've set `RuntimeMaxSec=604800` or seven days.

I suspected this would be an issue, and I guess it is. Systemd restarts your service every week, at which point it probably gets the last bunch of messages once again.

Have a look at [this](https://github.com/Kartoffel/pyserial-mqtt/blob/master/pyserial-mqtt.service) for a unit file that should work with most python scripts :)

Edit: I guess you've already figured this one out.

**Comment by bag-man** [comment]
Ah shit I didn't even realise that systemd unit was part of this repo. Thanks for spotting it too! I'll drop that and see what happens next week!

Thanks for the quick replies! Is it working well for you otherwise?

**Comment by Kartoffel** [comment]
Yep!

I didn't check to see if I had duplicates as I'm using it for some high-traffic subreddits but it's been running fine for weeks now.

**Comment by bag-man** [comment]
The MaxRuntimeSec must have been the issue due to how it seems to happen every week, but it is so strange that it does that... 

Anyway, glad it's working out for you. It seems like such a simple bit of code but it's made life so much easier for so many tasks!

**Pull request merged**
